name: exercise_3
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - mlflow=2.8.1
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - wandb==0.16.4
      - databricks_cli==0.8.7