channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - psutil==7.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.15.1
name: mlflow-env
